/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.campominado.view;

import com.campominado.controller.CampoVirtual;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ander
 */
public class FrameCampo extends javax.swing.JInternalFrame {

    private CampoVirtual campoVirtual;
    /**
     * Creates new form FrameCampo
     */
    public FrameCampo(String nivel) {
        initComponents();  
        gerarTabela(nivel);        
    }

    private void gerarTabela(String nivel){
        this.campoVirtual = new CampoVirtual(nivel);
        
        this.tblCampo.setTableHeader(null);
        this.tblCampo.setShowGrid(true);
        
        int quantidadeColunas = this.campoVirtual.getQuantidadeColunasCampo();
        int quantidadeLinhas = this.campoVirtual.getQuantidadeLinhasCampo();
                
        
        DefaultTableModel modelo = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable(int linha, int coluna){
                return false;
            }
        };
   
        for(int addColuna = 0; addColuna < quantidadeColunas; addColuna++){
            modelo.addColumn("");
        }
        
        for(int addLinha = 0; addLinha < quantidadeLinhas; addLinha++){
            modelo.addRow(new String[0]);
        }  
     
        this.tblCampo.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCampo = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        tblCampo.setBackground(new java.awt.Color(153, 153, 153));
        tblCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCampo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCampo.setCellSelectionEnabled(true);
        tblCampo.setGridColor(new java.awt.Color(0, 0, 0));
        tblCampo.setRowHeight(30);
        tblCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCampoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCampo);
        tblCampo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tblCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCampoMouseClicked
        int linha = this.tblCampo.getSelectedRow();
        int coluna = this.tblCampo.getSelectedColumn();
        
        int conteudo = this.campoVirtual.getPosicao(linha, coluna);
        
        //DefaultTableModel modelo = (DefaultTableModel) this.tblCampo.getModel();  
        
        if(conteudo > 0)
            this.tblCampo.getModel().setValueAt(conteudo, linha, coluna);
        else if(conteudo == 0){
            //PROGRAMAR AQUI
        }
        else {
            for(int numeroBomba = 0; numeroBomba < this.campoVirtual.getQuantidadeBombas(); numeroBomba++){
                this.tblCampo.getModel().setValueAt("*", this.campoVirtual.getBombas()[numeroBomba].getLinha(), this.campoVirtual.getBombas()[numeroBomba].getColuna());

            }
            JOptionPane.showMessageDialog(null, "Você Perdeu!");
        }
        
    }//GEN-LAST:event_tblCampoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCampo;
    // End of variables declaration//GEN-END:variables
}
