/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.campominado.view;

import com.campominado.bd.EstruturaBanco;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JInternalFrame;

/**
 *
 * @author ander
 */
public class Menu extends javax.swing.JFrame {

    private List<JInternalFrame> telas;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.telas = new ArrayList<JInternalFrame>();
        EstruturaBanco.createTablePartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        painelDesktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itnFacil = new javax.swing.JMenuItem();
        itnMedio = new javax.swing.JMenuItem();
        itnDificil = new javax.swing.JMenuItem();
        itnHistorico = new javax.swing.JMenuItem();
        itnSobre = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado");
        setName("frmPrincipal"); // NOI18N

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        menuInicio.setText("Início");

        jMenu4.setText("Novo Jogo");

        itnFacil.setText("Fácil");
        itnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnFacilActionPerformed(evt);
            }
        });
        jMenu4.add(itnFacil);

        itnMedio.setText("Médio");
        itnMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnMedioActionPerformed(evt);
            }
        });
        jMenu4.add(itnMedio);

        itnDificil.setText("Difícil");
        itnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnDificilActionPerformed(evt);
            }
        });
        jMenu4.add(itnDificil);

        menuInicio.add(jMenu4);

        itnHistorico.setText("Histórico");
        itnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnHistoricoActionPerformed(evt);
            }
        });
        menuInicio.add(itnHistorico);

        itnSobre.setText("Sobre");
        itnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnSobreActionPerformed(evt);
            }
        });
        menuInicio.add(itnSobre);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuInicio.add(jMenuItem1);

        jMenuBar2.add(menuInicio);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelDesktop)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnSobreActionPerformed
        this.fecharTelas();
        FrameSobre frameSobre = new FrameSobre();
        painelDesktop.add(frameSobre);
        frameSobre.setVisible(true);
        this.telas.add(frameSobre);
    }//GEN-LAST:event_itnSobreActionPerformed

    private void itnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnFacilActionPerformed
        this.fecharTelas();
        FrameCampo frameCampo = new FrameCampo("fácil");
        painelDesktop.add(frameCampo);
        frameCampo.setVisible(true);
        this.telas.add(frameCampo);
    }//GEN-LAST:event_itnFacilActionPerformed

    private void itnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnHistoricoActionPerformed
        this.fecharTelas();
        FrameHistorico frameHistorico = new FrameHistorico();
        painelDesktop.add(frameHistorico);        
        frameHistorico.setVisible(true);
        this.telas.add(frameHistorico);
    }//GEN-LAST:event_itnHistoricoActionPerformed

    private void itnMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnMedioActionPerformed
        this.fecharTelas();
        FrameCampo frameCampo = new FrameCampo("médio");
        painelDesktop.add(frameCampo);
        frameCampo.setVisible(true);
        this.telas.add(frameCampo);
    }//GEN-LAST:event_itnMedioActionPerformed

    private void itnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnDificilActionPerformed
        this.fecharTelas();
        FrameCampo frameCampo = new FrameCampo("difícil");
        painelDesktop.add(frameCampo);
        frameCampo.setVisible(true);
        this.telas.add(frameCampo);
    }//GEN-LAST:event_itnDificilActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void fecharTelas(){
        for(JInternalFrame tela : this.telas){
            tela.dispose();
        }
        this.telas.clear();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itnDificil;
    private javax.swing.JMenuItem itnFacil;
    private javax.swing.JMenuItem itnHistorico;
    private javax.swing.JMenuItem itnMedio;
    private javax.swing.JMenuItem itnSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JDesktopPane painelDesktop;
    // End of variables declaration//GEN-END:variables
}
