/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.campominado.view;

import com.campominado.controller.CampoVirtual;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ander
 */
public class Menu extends javax.swing.JFrame {

    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        painelDesktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itnFacil = new javax.swing.JMenuItem();
        itnMedio = new javax.swing.JMenuItem();
        itnDificil = new javax.swing.JMenuItem();
        itnHistorico = new javax.swing.JMenuItem();
        itnSobre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado");
        setName("frmPrincipal"); // NOI18N

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        menuInicio.setText("Início");

        jMenu4.setText("Novo Jogo");

        itnFacil.setText("Fácil");
        itnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnFacilActionPerformed(evt);
            }
        });
        jMenu4.add(itnFacil);

        itnMedio.setText("Médio");
        jMenu4.add(itnMedio);

        itnDificil.setText("Difícil");
        jMenu4.add(itnDificil);

        menuInicio.add(jMenu4);

        itnHistorico.setText("Histórico");
        menuInicio.add(itnHistorico);

        itnSobre.setText("Sobre");
        itnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itnSobreActionPerformed(evt);
            }
        });
        menuInicio.add(itnSobre);

        jMenuBar2.add(menuInicio);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDesktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnSobreActionPerformed
       FrameSobre frameSobre = new FrameSobre();
       painelDesktop.add(frameSobre);
       frameSobre.setVisible(true);
    }//GEN-LAST:event_itnSobreActionPerformed

    private void itnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itnFacilActionPerformed
        FrameCampo frameCampo = new FrameCampo();
        painelDesktop.add(frameCampo);
        frameCampo.setVisible(true);
    }//GEN-LAST:event_itnFacilActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
//                        JPanel panel = new JPanel(new GridLayout());
//
//                JButton botao = new JButton("botao");
                //botao.setVisible(true);


//                panelCampo = new JPanel(new GridLayout());
//                panelCampo.add(botao);
                
//                JPanel panel = new JPanel(new GridLayout());
//        
//                JButton botao = new JButton("botao");
//                panel.add(botao);
//                
//                CampoVirtual campoVirtual = new CampoVirtual();
//                campoVirtual.exibirCampo();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itnDificil;
    private javax.swing.JMenuItem itnFacil;
    private javax.swing.JMenuItem itnHistorico;
    private javax.swing.JMenuItem itnMedio;
    private javax.swing.JMenuItem itnSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JDesktopPane painelDesktop;
    // End of variables declaration//GEN-END:variables
}
